# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chargeVehiclePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowOperatorCharge(object):
    def setupUi(self, MainWindowOperatorCharge):
        MainWindowOperatorCharge.setObjectName("MainWindowOperatorCharge")
        MainWindowOperatorCharge.resize(977, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Users/Calvin Pfob/Documents/guiDevelopment/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowOperatorCharge.setWindowIcon(icon)
        MainWindowOperatorCharge.setIconSize(QtCore.QSize(25, 25))
        self.operatorChargePage = QtWidgets.QWidget(MainWindowOperatorCharge)
        self.operatorChargePage.setObjectName("operatorChargePage")
        self.title = QtWidgets.QLabel(self.operatorChargePage)
        self.title.setGeometry(QtCore.QRect(0, 10, 981, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.backgroundPicture = QtWidgets.QLabel(self.operatorChargePage)
        self.backgroundPicture.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.backgroundPicture.setStyleSheet("background-image: url(:/login/tier-mobility-2021-05-min.png);")
        self.backgroundPicture.setText("")
        self.backgroundPicture.setPixmap(QtGui.QPixmap(":/login/tier-mobility-2021-05-min.png"))
        self.backgroundPicture.setScaledContents(True)
        self.backgroundPicture.setObjectName("backgroundPicture")
        self.backgroundFrame = QtWidgets.QFrame(self.operatorChargePage)
        self.backgroundFrame.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.backgroundFrame.setStyleSheet("background:rgba(0, 0, 0, 50)")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.chargeConfirmButton = QtWidgets.QPushButton(self.backgroundFrame)
        self.chargeConfirmButton.setGeometry(QtCore.QRect(210, 350, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.chargeConfirmButton.setFont(font)
        self.chargeConfirmButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.chargeConfirmButton.setObjectName("chargeConfirmButton")
        self.thresholdEntry = QtWidgets.QLineEdit(self.backgroundFrame)
        self.thresholdEntry.setGeometry(QtCore.QRect(400, 160, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.thresholdEntry.setFont(font)
        self.thresholdEntry.setStyleSheet("background-color:white")
        self.thresholdEntry.setText("")
        self.thresholdEntry.setObjectName("thresholdEntry")
        self.chargeDescriptionLabel = QtWidgets.QLabel(self.backgroundFrame)
        self.chargeDescriptionLabel.setGeometry(QtCore.QRect(250, 230, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.chargeDescriptionLabel.setFont(font)
        self.chargeDescriptionLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.chargeDescriptionLabel.setObjectName("chargeDescriptionLabel")
        self.thresholdLabel = QtWidgets.QLabel(self.backgroundFrame)
        self.thresholdLabel.setGeometry(QtCore.QRect(250, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.thresholdLabel.setFont(font)
        self.thresholdLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.backButton = QtWidgets.QPushButton(self.backgroundFrame)
        self.backButton.setGeometry(QtCore.QRect(500, 350, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.backButton.setObjectName("backButton")
        self.backgroundPicture.raise_()
        self.backgroundFrame.raise_()
        self.title.raise_()
        MainWindowOperatorCharge.setCentralWidget(self.operatorChargePage)

        self.retranslateUi(MainWindowOperatorCharge)
        QtCore.QMetaObject.connectSlotsByName(MainWindowOperatorCharge)

    def retranslateUi(self, MainWindowOperatorCharge):
        _translate = QtCore.QCoreApplication.translate
        MainWindowOperatorCharge.setWindowTitle(_translate("MainWindowOperatorCharge", "E-Vehicle Share System"))
        self.title.setText(_translate("MainWindowOperatorCharge", "<html><head/><body><p><span style=\" font-size:36pt; color:#ffffff;\">Charge Vehicle</span></p></body></html>"))
        self.chargeConfirmButton.setText(_translate("MainWindowOperatorCharge", "Charge"))
        self.chargeDescriptionLabel.setText(_translate("MainWindowOperatorCharge", "Note: battery less than or equal to threshold value will be charged"))
        self.thresholdLabel.setText(_translate("MainWindowOperatorCharge", "Threshold: (0-1)"))
        self.backButton.setText(_translate("MainWindowOperatorCharge", "Back"))
import bg_rc
