# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customerPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowCustomer(object):
    def setupUi(self, MainWindowCustomer):
        MainWindowCustomer.setObjectName("MainWindowCustomer")
        MainWindowCustomer.resize(977, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Users/Calvin Pfob/Documents/guiDevelopment/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowCustomer.setWindowIcon(icon)
        MainWindowCustomer.setIconSize(QtCore.QSize(25, 25))
        self.customerPage = QtWidgets.QWidget(MainWindowCustomer)
        self.customerPage.setObjectName("customerPage")
        self.title = QtWidgets.QLabel(self.customerPage)
        self.title.setGeometry(QtCore.QRect(0, 10, 981, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.backgroundPicture = QtWidgets.QLabel(self.customerPage)
        self.backgroundPicture.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.backgroundPicture.setStyleSheet("background-image: url(:/login/tier-mobility-2021-05-min.png);")
        self.backgroundPicture.setText("")
        self.backgroundPicture.setPixmap(QtGui.QPixmap(":/login/tier-mobility-2021-05-min.png"))
        self.backgroundPicture.setScaledContents(True)
        self.backgroundPicture.setObjectName("backgroundPicture")
        self.backgroundFrame = QtWidgets.QFrame(self.customerPage)
        self.backgroundFrame.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.backgroundFrame.setStyleSheet("background:rgba(0, 0, 0, 50)")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.labelQuestion = QtWidgets.QLabel(self.backgroundFrame)
        self.labelQuestion.setGeometry(QtCore.QRect(70, 130, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelQuestion.setFont(font)
        self.labelQuestion.setStyleSheet("color:rgb(255, 255, 255)")
        self.labelQuestion.setObjectName("labelQuestion")
        self.rentVehicleButton = QtWidgets.QPushButton(self.backgroundFrame)
        self.rentVehicleButton.setGeometry(QtCore.QRect(380, 130, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rentVehicleButton.setFont(font)
        self.rentVehicleButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.rentVehicleButton.setObjectName("rentVehicleButton")
        self.topUpBalanceButton = QtWidgets.QPushButton(self.backgroundFrame)
        self.topUpBalanceButton.setGeometry(QtCore.QRect(380, 250, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.topUpBalanceButton.setFont(font)
        self.topUpBalanceButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.topUpBalanceButton.setObjectName("topUpBalanceButton")
        self.signOutButton = QtWidgets.QPushButton(self.customerPage)
        self.signOutButton.setGeometry(QtCore.QRect(810, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.signOutButton.setFont(font)
        self.signOutButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.signOutButton.setObjectName("signOutButton")
        self.backgroundPicture.raise_()
        self.backgroundFrame.raise_()
        self.title.raise_()
        self.signOutButton.raise_()
        MainWindowCustomer.setCentralWidget(self.customerPage)

        self.retranslateUi(MainWindowCustomer)
        QtCore.QMetaObject.connectSlotsByName(MainWindowCustomer)

    def retranslateUi(self, MainWindowCustomer):
        _translate = QtCore.QCoreApplication.translate
        MainWindowCustomer.setWindowTitle(_translate("MainWindowCustomer", "E-Vehicle Share System"))
        self.title.setText(_translate("MainWindowCustomer", "<html><head/><body><p><span style=\" font-size:36pt; color:#ffffff;\">Welcome Customer</span></p></body></html>"))
        self.labelQuestion.setText(_translate("MainWindowCustomer", "What can we do for you today?:"))
        self.rentVehicleButton.setText(_translate("MainWindowCustomer", "Rent Vehicle"))
        self.topUpBalanceButton.setText(_translate("MainWindowCustomer", "Top-Up Balance"))
        self.signOutButton.setText(_translate("MainWindowCustomer", "Sign out"))
import bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowCustomer = QtWidgets.QMainWindow()
    ui = Ui_MainWindowCustomer()
    ui.setupUi(MainWindowCustomer)
    MainWindowCustomer.show()
    sys.exit(app.exec_())
