# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moveVehiclePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowOperatorMoveVehicle(object):
    def setupUi(self, MainWindowOperatorMoveVehicle):
        MainWindowOperatorMoveVehicle.setObjectName("MainWindowOperatorMoveVehicle")
        MainWindowOperatorMoveVehicle.resize(977, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Users/Calvin Pfob/Documents/guiDevelopment/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowOperatorMoveVehicle.setWindowIcon(icon)
        MainWindowOperatorMoveVehicle.setIconSize(QtCore.QSize(25, 25))
        self.operatorMoveVehiclePage = QtWidgets.QWidget(MainWindowOperatorMoveVehicle)
        self.operatorMoveVehiclePage.setStyleSheet("")
        self.operatorMoveVehiclePage.setObjectName("operatorMoveVehiclePage")
        self.title = QtWidgets.QLabel(self.operatorMoveVehiclePage)
        self.title.setGeometry(QtCore.QRect(0, 10, 981, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.backgroundPicture = QtWidgets.QLabel(self.operatorMoveVehiclePage)
        self.backgroundPicture.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.backgroundPicture.setStyleSheet("background-image: url(:/login/tier-mobility-2021-05-min.png);")
        self.backgroundPicture.setText("")
        self.backgroundPicture.setPixmap(QtGui.QPixmap(":/login/tier-mobility-2021-05-min.png"))
        self.backgroundPicture.setScaledContents(True)
        self.backgroundPicture.setObjectName("backgroundPicture")
        self.backgroundFrame = QtWidgets.QFrame(self.operatorMoveVehiclePage)
        self.backgroundFrame.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.backgroundFrame.setStyleSheet("background:rgba(0, 0, 0, 50)")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.moveButton = QtWidgets.QPushButton(self.backgroundFrame)
        self.moveButton.setGeometry(QtCore.QRect(250, 310, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.moveButton.setFont(font)
        self.moveButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.moveButton.setObjectName("moveButton")
        self.vehicleIDLabel = QtWidgets.QLabel(self.backgroundFrame)
        self.vehicleIDLabel.setGeometry(QtCore.QRect(310, 140, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vehicleIDLabel.setFont(font)
        self.vehicleIDLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.vehicleIDLabel.setObjectName("vehicleIDLabel")
        self.cityLocationLabel = QtWidgets.QLabel(self.backgroundFrame)
        self.cityLocationLabel.setGeometry(QtCore.QRect(300, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cityLocationLabel.setFont(font)
        self.cityLocationLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.cityLocationLabel.setObjectName("cityLocationLabel")
        self.comboBoxVehicle = QtWidgets.QComboBox(self.backgroundFrame)
        self.comboBoxVehicle.setGeometry(QtCore.QRect(450, 140, 291, 31))
        self.comboBoxVehicle.setStyleSheet("background-color: white")
        self.comboBoxVehicle.setMaxVisibleItems(5)
        self.comboBoxVehicle.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBoxVehicle.setObjectName("comboBoxVehicle")
        self.comboBoxCitylocation = QtWidgets.QComboBox(self.backgroundFrame)
        self.comboBoxCitylocation.setGeometry(QtCore.QRect(450, 209, 291, 31))
        self.comboBoxCitylocation.setStyleSheet("background-color: white")
        self.comboBoxCitylocation.setMaxVisibleItems(5)
        self.comboBoxCitylocation.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBoxCitylocation.setObjectName("comboBoxCitylocation")
        self.backButton = QtWidgets.QPushButton(self.backgroundFrame)
        self.backButton.setGeometry(QtCore.QRect(570, 310, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.backButton.setObjectName("backButton")
        self.backgroundPicture.raise_()
        self.backgroundFrame.raise_()
        self.title.raise_()
        MainWindowOperatorMoveVehicle.setCentralWidget(self.operatorMoveVehiclePage)

        self.retranslateUi(MainWindowOperatorMoveVehicle)
        QtCore.QMetaObject.connectSlotsByName(MainWindowOperatorMoveVehicle)

    def retranslateUi(self, MainWindowOperatorMoveVehicle):
        _translate = QtCore.QCoreApplication.translate
        MainWindowOperatorMoveVehicle.setWindowTitle(_translate("MainWindowOperatorMoveVehicle", "E-Vehicle Share System"))
        self.title.setText(_translate("MainWindowOperatorMoveVehicle", "<html><head/><body><p><span style=\" font-size:36pt; color:#ffffff;\">Move Vehicle</span></p></body></html>"))
        self.moveButton.setText(_translate("MainWindowOperatorMoveVehicle", "Move"))
        self.vehicleIDLabel.setText(_translate("MainWindowOperatorMoveVehicle", "Vehicle ID"))
        self.cityLocationLabel.setText(_translate("MainWindowOperatorMoveVehicle", "CityLocation"))
        self.backButton.setText(_translate("MainWindowOperatorMoveVehicle", "Back"))
import bg_rc
