# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trackVehiclePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowOperatorTrackVehicle(object):
    def setupUi(self, MainWindowOperatorTrackVehicle):
        MainWindowOperatorTrackVehicle.setObjectName("MainWindowOperatorTrackVehicle")
        MainWindowOperatorTrackVehicle.resize(977, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Users/Calvin Pfob/Documents/guiDevelopment/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowOperatorTrackVehicle.setWindowIcon(icon)
        MainWindowOperatorTrackVehicle.setIconSize(QtCore.QSize(25, 25))
        self.operatorTrackVehiclePage = QtWidgets.QWidget(MainWindowOperatorTrackVehicle)
        self.operatorTrackVehiclePage.setStyleSheet("")
        self.operatorTrackVehiclePage.setObjectName("operatorTrackVehiclePage")
        self.title = QtWidgets.QLabel(self.operatorTrackVehiclePage)
        self.title.setGeometry(QtCore.QRect(0, 10, 981, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.backgroundPicture = QtWidgets.QLabel(self.operatorTrackVehiclePage)
        self.backgroundPicture.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.backgroundPicture.setStyleSheet("background-image: url(:/login/tier-mobility-2021-05-min.png);")
        self.backgroundPicture.setText("")
        self.backgroundPicture.setPixmap(QtGui.QPixmap(":/login/tier-mobility-2021-05-min.png"))
        self.backgroundPicture.setScaledContents(True)
        self.backgroundPicture.setObjectName("backgroundPicture")
        self.backgroundFrame = QtWidgets.QFrame(self.operatorTrackVehiclePage)
        self.backgroundFrame.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.backgroundFrame.setStyleSheet("background:rgba(0, 0, 0, 50)")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.trackButton = QtWidgets.QPushButton(self.backgroundFrame)
        self.trackButton.setGeometry(QtCore.QRect(550, 70, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.trackButton.setFont(font)
        self.trackButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.trackButton.setObjectName("trackButton")
        self.vehicleIDLabel = QtWidgets.QLabel(self.backgroundFrame)
        self.vehicleIDLabel.setGeometry(QtCore.QRect(170, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vehicleIDLabel.setFont(font)
        self.vehicleIDLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.vehicleIDLabel.setObjectName("vehicleIDLabel")
        self.cityLocationLabel = QtWidgets.QLabel(self.backgroundFrame)
        self.cityLocationLabel.setGeometry(QtCore.QRect(160, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cityLocationLabel.setFont(font)
        self.cityLocationLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.cityLocationLabel.setObjectName("cityLocationLabel")
        self.comboBoxVehicle = QtWidgets.QComboBox(self.backgroundFrame)
        self.comboBoxVehicle.setGeometry(QtCore.QRect(270, 70, 201, 31))
        self.comboBoxVehicle.setStyleSheet("background-color: white")
        self.comboBoxVehicle.setMaxVisibleItems(5)
        self.comboBoxVehicle.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBoxVehicle.setObjectName("comboBoxVehicle")
        self.comboBoxCitylocation = QtWidgets.QComboBox(self.backgroundFrame)
        self.comboBoxCitylocation.setGeometry(QtCore.QRect(270, 120, 201, 31))
        self.comboBoxCitylocation.setStyleSheet("background-color: white")
        self.comboBoxCitylocation.setMaxVisibleItems(5)
        self.comboBoxCitylocation.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBoxCitylocation.setObjectName("comboBoxCitylocation")
        self.backButton = QtWidgets.QPushButton(self.backgroundFrame)
        self.backButton.setGeometry(QtCore.QRect(550, 120, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgba(85, 153, 255, 150); color: white")
        self.backButton.setObjectName("backButton")
        self.scrollArea = QtWidgets.QScrollArea(self.backgroundFrame)
        self.scrollArea.setGeometry(QtCore.QRect(170, 180, 621, 261))
        self.scrollArea.setStyleSheet("background-color: white")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 621, 261))
        self.textEdit.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.textEdit.setObjectName("textEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.backgroundPicture.raise_()
        self.backgroundFrame.raise_()
        self.title.raise_()
        MainWindowOperatorTrackVehicle.setCentralWidget(self.operatorTrackVehiclePage)

        self.retranslateUi(MainWindowOperatorTrackVehicle)
        QtCore.QMetaObject.connectSlotsByName(MainWindowOperatorTrackVehicle)

    def retranslateUi(self, MainWindowOperatorTrackVehicle):
        _translate = QtCore.QCoreApplication.translate
        MainWindowOperatorTrackVehicle.setWindowTitle(_translate("MainWindowOperatorTrackVehicle", "E-Vehicle Share System"))
        self.title.setText(_translate("MainWindowOperatorTrackVehicle", "<html><head/><body><p><span style=\" font-size:36pt; color:#ffffff;\">Track Vehicle</span></p></body></html>"))
        self.trackButton.setText(_translate("MainWindowOperatorTrackVehicle", "Track"))
        self.vehicleIDLabel.setText(_translate("MainWindowOperatorTrackVehicle", "Vehicle ID"))
        self.cityLocationLabel.setText(_translate("MainWindowOperatorTrackVehicle", "CityLocation"))
        self.backButton.setText(_translate("MainWindowOperatorTrackVehicle", "Back"))
        self.textEdit.setHtml(_translate("MainWindowOperatorTrackVehicle", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
import bg_rc
